#!/usr/bin/env python
"""Generate an object tag map for a cube with a tag centred on each face.

    ./venv/bin/python make_cube_map.py --size 0.05 --tag-size 0.03 \
        --faces +X -X +Y -Y +Z --start-id 10 --out cube_tags.yaml

The cube frame has its origin at the cube's CENTRE, axes X forward, Y left,
Z up -- the same convention as base_assy, so an identity object pose means the
cube is sitting axis-aligned with the arm base.

Face rotations are derived here rather than hardcoded: for each face the tag's
+Z is set to the outward normal and its printed +Y to a chosen "up" direction,
then the rotation matrix is converted to extrinsic-XYZ rpy. Deriving it keeps
the six faces guaranteed consistent with each other and with the tag frame
convention in tag_map.py.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from scipy.spatial.transform import Rotation

# face name -> (outward normal, which cube axis the tag's printed "up" follows)
FACES = {
    "+X": ([1, 0, 0], [0, 0, 1]),
    "-X": ([-1, 0, 0], [0, 0, 1]),
    "+Y": ([0, 1, 0], [0, 0, 1]),
    "-Y": ([0, -1, 0], [0, 0, 1]),
    "+Z": ([0, 0, 1], [1, 0, 0]),
    "-Z": ([0, 0, -1], [1, 0, 0]),
}


def _face_list(text: str) -> list[str]:
    faces = [f.strip() for f in text.split(",") if f.strip()]
    bad = [f for f in faces if f not in FACES]
    if bad:
        raise argparse.ArgumentTypeError(
            f"unknown face(s) {bad}; choose from {list(FACES)}")
    if len(set(faces)) != len(faces):
        raise argparse.ArgumentTypeError("duplicate face listed")
    return faces


def face_pose(face: str, cube_size: float) -> tuple[np.ndarray, np.ndarray]:
    """(centre xyz, rpy) of a tag centred on one cube face, in the cube frame."""
    normal, up = (np.asarray(v, dtype=np.float64) for v in FACES[face])
    z = normal / np.linalg.norm(normal)          # tag +Z = outward face normal
    y = up - np.dot(up, z) * z                   # tag +Y = printed "up"
    y /= np.linalg.norm(y)
    x = np.cross(y, z)                           # right-handed
    R = np.column_stack([x, y, z])
    return z * (cube_size / 2.0), Rotation.from_matrix(R).as_euler("xyz")


def build(args) -> str:
    if args.tag_size >= args.size:
        raise SystemExit(
            f"tag size {args.tag_size} m does not fit on a {args.size} m face"
        )
    if args.tag_size > args.size * 0.9:
        print(
            f"  [warn] tag {args.tag_size} m on a {args.size} m face leaves almost "
            "no white quiet zone; detection will suffer. Aim for ~70% of the face."
        )

    lines = [
        "schema: apriltag_map/1",
        "frame_id: cube",
        "units: {length: m, angle: rad}",
        f"family: {args.family}",
        f"default_size: {args.tag_size:g}",
        "",
        f"# Cube of edge {args.size:g} m. Origin at the cube CENTRE;",
        "# axes X forward, Y left, Z up (same convention as base_assy).",
        "# Generated by make_cube_map.py -- face rotations are derived, not typed.",
        "#",
        "# Tag ids MUST NOT collide with the base map (tags_base_assy.yaml).",
        "# scene_solve.check_disjoint() refuses to run if they do.",
        "#",
        "# Print each tag at exactly the size above, measured across the BLACK",
        "# BORDER, and centre it on its face. A tag glued on crooked or off-centre",
        "# is indistinguishable from a bad solve until you check reprojection rms.",
        "",
        "tags:",
    ]

    for i, face in enumerate(args.faces):
        xyz, rpy = face_pose(face, args.size)
        tag_id = args.start_id + i
        lines.append(
            f"  - {{id: {tag_id}, "
            f"xyz: [{xyz[0]:+.5f}, {xyz[1]:+.5f}, {xyz[2]:+.5f}], "
            f"rpy: [{rpy[0]:+.5f}, {rpy[1]:+.5f}, {rpy[2]:+.5f}], "
            f'note: "{face} face"}}'
        )

    lines += [
        "",
        "# Where the gripper should end up, in the CUBE's frame. The cube origin",
        "# is its centre, which is inside the cube -- so an offset is essential.",
        "# Default below: the centre itself, which suits a gripper that closes on",
        "# two opposite faces. Raise z to grip nearer the top.",
        "grasp:",
        f"  xyz: [{args.grasp_xyz[0]:+.5f}, {args.grasp_xyz[1]:+.5f}, "
        f"{args.grasp_xyz[2]:+.5f}]",
        f"  rpy: [{args.grasp_rpy[0]:+.5f}, {args.grasp_rpy[1]:+.5f}, "
        f"{args.grasp_rpy[2]:+.5f}]",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--size", type=float, required=True, help="cube edge length, m")
    p.add_argument("--tag-size", type=float, required=True,
                   help="tag black-border edge length, m")
    # Comma-separated rather than nargs="+": argparse would parse a bare "-X"
    # as an option flag.
    p.add_argument("--faces", type=_face_list, default=list(FACES)[:5],
                   help="comma-separated faces carrying a tag, e.g. +X,-X,+Y,-Y,+Z")
    p.add_argument("--start-id", type=int, default=10,
                   help="first tag id; must not collide with the base map")
    p.add_argument("--family", default="tag36h11")
    p.add_argument("--grasp-xyz", type=float, nargs=3, default=[0.0, 0.0, 0.0],
                   help="grasp point in the cube frame, m")
    p.add_argument("--grasp-rpy", type=float, nargs=3, default=[0.0, 0.0, 0.0],
                   help="grasp orientation in the cube frame, rad")
    p.add_argument("--out", type=Path, default=Path("cube_tags.yaml"))
    args = p.parse_args(argv)

    text = build(args)
    args.out.write_text(text)
    print(text)
    print(f"  wrote {args.out}")
    print(f"  {len(args.faces)} faces, tag ids "
          f"{args.start_id}..{args.start_id + len(args.faces) - 1}")
    print("\n  Reminder: the solver needs TWO faces visible at once. Position the")
    print("  camera to look at a corner of the cube, not square at one face --")
    print("  a single face is coplanar and has a two-fold pose ambiguity.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
